### ISSUE TITLE
Update to 2018.3.6

### ISSUE THREAD

**Issue by Arnaud-Dorthe** [flathub/org.flightgear.FlightGear#17]
The latest stable, supported release.

**Comment by Vanadiae** [comment]
https://github.com/flathub/org.flightgear.FlightGear/pull/16 is in the work currently. Can you close this issue please, as there is already #14 opened ?

BTW @bilelmoussaoui can I have maintainer role of this repository, so I can close issues and review/merge MRs (maintainance, really) ? @Alexander-Wilms doesn't seems to be still active these days (he's done some great job bringing it to flathub though ;), and I helped getting #13 merged and also trying to get #16 done, and am willing to continue doing stuff on this flatpak, as I use this simulator and like it ;)

**Comment by Arnaud-Dorthe** [comment]
Well, thank you for your implication on #16 but the current stable release is 2018.3.6.
Neither the 2020.1.3 nor the 2019.1.1 are considered stable yet.

**Comment by Vanadiae** [comment]
Well, as of the front page of flightgear.org, 
![Capture d’écran de 2020-09-15 19-27-21](https://user-images.githubusercontent.com/48521955/93244321-d6876880-f789-11ea-80d8-781b344d812e.png). If they made a release, it's that it's usable. When they say that 2018.3.6 is the "stable" release, it means it's an LTS basically (the next one will be [2020.2](http://wiki.flightgear.org/Post_FlightGear_2020.2_LTS_changes)). But since 2020.1.3 is released and seems quite stable (while having some nice new features!), it's IMO good to update to this version.

**Comment by Vanadiae** [comment]
I'm gonna close this issue, as I merged the well-working #16 version (2020.1.3), so there is no longer any point in keeping this issue opened.

**Comment by Arnaud-Dorthe** [comment]
Ok for me.
