### ISSUE TITLE
Segmentation fault on launch (2020.3.3)

### ISSUE THREAD

**Issue by jacobzimmermann** [flathub/org.flightgear.FlightGear#25]
Since the flatpak package updated to 2020.3.3, it became impossible to run FlightGear:

```
flatpak run org.flightgear.FlightGear
Gtk-Message: 16:50:34.222: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:50:34.222: Failed to load module "unity-gtk-module"
Gtk-Message: 16:50:34.222: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:50:34.222: Failed to load module "unity-gtk-module"
    0.05 [WARN]:gui        Qt: Session management error: None of the authentication protocols specified are supported
Now checking for plug-in osgPlugins-3.6.5/osgdb_nvtt.so
    4.30 [WARN]:general    Enabling ATI/AMD viewport hack
    4.40 [INFO]:terrasync  Starting automatic scenery download/synchronization to '/home/jzimm/.fgfs/TerraSync'.
/app/bin/flightgear.sh: line 2:     3 Segmentation fault      (core dumped) fgfs --launcher "$@"
```

This happens on both Wayland and X11 sessions. I'm running Ubuntu 20.10.

**Comment by Vanadiae** [comment]
Hi!

Can you run `flatpak install org.kde.Sdk//5.15`  in a terminal, then launch flightgear once and after that try running `flatpak-coredumpctl org.flightgear.Flightgear`, and paste here the output of this last command. Those commands will gather the informations/logs explaining what went wrong. Note that the first command will install a few hundreds of megabytes of data. It *might* also require installing `org.flightgear.FlightGear.Debug` but I'm not sure (try without it and if it says there's some missing pieces you can try installing it too).

This will help me figure out what's wrong, and eventually fix it (if the problem is on our side).

**Comment by jacobzimmermann** [comment]
I tried what you suggest but that doesn't seem to do anything:

`
$ flatpak-coredumpctl org.flightgear.Flightgear
Traceback (most recent call last):
  File "/usr/bin/flatpak-coredumpctl", line 83, in <module>
    coredumper.run()
  File "/usr/bin/flatpak-coredumpctl", line 44, in run
    subprocess.check_call(["coredumpctl", "dump"] + shlex.split(self.coredumpctl_matches),
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['coredumpctl', 'dump']' returned non-zero exit status 1.
`

**Comment by violetmage** [comment]
+1

is same problem am having

am incorrectly identify first, however am know certain problem is of terrasync

**Comment by violetmage** [comment]
flightgear is working with no problems, when running without terrasync

for now, am guessing is dependancy problem

**Comment by violetmage** [comment]
aha

is flightgear bug

they have make hotfix:
[https://sourceforge.net/p/flightgear/codetickets/2434/](url)

am guessing is include in new 2020.3.4

going to make pull request...

**Comment by jacobzimmermann** [comment]
Indeed it is a terrasync problem. Disabling terrasync solves it for me too,

**Comment by Vanadiae** [comment]
Normally if you update and try again it shouldn't crash anymore @jacobzimmermann.
